<?php

namespace Database\Seeders;

use App\Models\RoleRoute;
use Illuminate\Database\Seeder;

class RoleRouteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        RoleRoute::insert([
            ['role_id' => 1, 'name' => 'admin.dashboard'],
            ['role_id' => 1, 'name' => 'admin.comp-add-bal'],
            ['role_id' => 1, 'name' => 'admin.comp-sub-bal'],
            ['role_id' => 2, 'name' => 'admin.setting.index'],
            ['role_id' => 2, 'name' => 'admin.setting.store'],
            ['role_id' => 2, 'name' => 'admin.setting.update'],
            ['role_id' => 2, 'name' => 'admin.setting.edit'],
            ['role_id' => 2, 'name' => 'admin.setting.destroy'],
            ['role_id' => 2, 'name' => 'admin.setting.show'],
            ['role_id' => 3, 'name' => 'admin.profile.index'],
            ['role_id' => 3, 'name' => 'admin.profile.store'],
            ['role_id' => 3, 'name' => 'admin.profile.store'],
            ['role_id' => 3, 'name' => 'admin.profile.update'],
            ['role_id' => 3, 'name' => 'admin.profile.edit'],
            ['role_id' => 3, 'name' => 'admin.profile.destroy'],
            ['role_id' => 3, 'name' => 'admin.profile.show'],
            ['role_id' => 4, 'name' => 'admin.account-approval.index'],
            ['role_id' => 4, 'name' => 'admin.account-approval.store'],
            ['role_id' => 4, 'name' => 'admin.account-approval.update'],
            ['role_id' => 4, 'name' => 'admin.account-approval.edit'],
            ['role_id' => 4, 'name' => 'admin.account-approval.destroy'],
            ['role_id' => 4, 'name' => 'admin.account-approval.show'],
            ['role_id' => 5, 'name' => 'admin.product.index'],
            ['role_id' => 5, 'name' => 'admin.product.store'],
            ['role_id' => 5, 'name' => 'admin.product.update'],
            ['role_id' => 5, 'name' => 'admin.product.edit'],
            ['role_id' => 5, 'name' => 'admin.product.destroy'],
            ['role_id' => 5, 'name' => 'admin.product.show'],
            ['role_id' => 5, 'name' => 'admin.image.destroy'],
            ['role_id' => 5, 'name' => 'admin.image.update'],
            ['role_id' => 6, 'name' => 'admin.category.index'],
            ['role_id' => 6, 'name' => 'admin.category.store'],
            ['role_id' => 6, 'name' => 'admin.category.update'],
            ['role_id' => 6, 'name' => 'admin.category.edit'],
            ['role_id' => 6, 'name' => 'admin.category.destroy'],
            ['role_id' => 6, 'name' => 'admin.category.show'],
            ['role_id' => 7, 'name' => 'admin.subcategory.index'],
            ['role_id' => 7, 'name' => 'admin.subcategory.store'],
            ['role_id' => 7, 'name' => 'admin.subcategory.update'],
            ['role_id' => 7, 'name' => 'admin.subcategory.edit'],
            ['role_id' => 7, 'name' => 'admin.subcategory.destroy'],
            ['role_id' => 7, 'name' => 'admin.subcategory.show'],
            ['role_id' => 8, 'name' => 'admin.user.index'],
            ['role_id' => 8, 'name' => 'admin.user.store'],
            ['role_id' => 8, 'name' => 'admin.user.update'],
            ['role_id' => 8, 'name' => 'admin.user.edit'],
            ['role_id' => 8, 'name' => 'admin.user.destroy'],
            ['role_id' => 8, 'name' => 'admin.user.show'],
            ['role_id' => 8, 'name' => 'admin.user.addbalance'],
            ['role_id' => 8, 'name' => 'admin.user.subbalance'],
            ['role_id' => 8, 'name' => 'admin.user-accounts'],
            ['role_id' => 8, 'name' => 'admin.order.user'],
            ['role_id' => 9, 'name' => 'admin.vendor.index'],
            ['role_id' => 9, 'name' => 'admin.vendor.store'],
            ['role_id' => 9, 'name' => 'admin.vendor.update'],
            ['role_id' => 9, 'name' => 'admin.vendor.edit'],
            ['role_id' => 9, 'name' => 'admin.vendor.destroy'],
            ['role_id' => 9, 'name' => 'admin.vendor.show'],
            ['role_id' => 9, 'name' => 'admin.addbalance'],
            ['role_id' => 9, 'name' => 'admin.subbalance'],
            ['role_id' => 9, 'name' => 'admin.vendorproducts'],
            
            ['role_id' => 10, 'name' => 'admin.gateway.index'],
            ['role_id' => 10, 'name' => 'admin.gateway.store'],
            ['role_id' => 10, 'name' => 'admin.gateway.update'],
            ['role_id' => 10, 'name' => 'admin.gateway.edit'],
            ['role_id' => 10, 'name' => 'admin.gateway.destroy'],
            ['role_id' => 10, 'name' => 'admin.gateway.show'],
            ['role_id' => 11, 'name' => 'admin.deposit-method.index'],
            ['role_id' => 11, 'name' => 'admin.deposit-method.store'],
            ['role_id' => 11, 'name' => 'admin.deposit-method.update'],
            ['role_id' => 11, 'name' => 'admin.deposit-method.edit'],
            ['role_id' => 11, 'name' => 'admin.deposit-method.destroy'],
            ['role_id' => 11, 'name' => 'admin.deposit-method.show'],
            ['role_id' => 12, 'name' => 'admin.withdrawmethod.index'],
            ['role_id' => 12, 'name' => 'admin.withdrawmethod.store'],
            ['role_id' => 12, 'name' => 'admin.withdrawmethod.update'],
            ['role_id' => 12, 'name' => 'admin.withdrawmethod.edit'],
            ['role_id' => 12, 'name' => 'admin.withdrawmethod.destroy'],
            ['role_id' => 12, 'name' => 'admin.withdrawmethod.show'],
            ['role_id' => 13, 'name' => 'admin.contact.create'],
            ['role_id' => 13, 'name' => 'admin.contact.index'],
            ['role_id' => 13, 'name' => 'admin.contact.store'],
            ['role_id' => 13, 'name' => 'admin.contact.update'],
            ['role_id' => 13, 'name' => 'admin.contact.edit'],
            ['role_id' => 13, 'name' => 'admin.contact.destroy'],
            ['role_id' => 13, 'name' => 'admin.contact.show'],
            ['role_id' => 14, 'name' => 'admin.admins.index'],
            ['role_id' => 14, 'name' => 'admin.admins.store'],
            ['role_id' => 14, 'name' => 'admin.admins.update'],
            ['role_id' => 14, 'name' => 'admin.admins.edit'],
            ['role_id' => 14, 'name' => 'admin.admins.destroy'],
            ['role_id' => 14, 'name' => 'admin.admins.show'],
            ['role_id' => 15, 'name' => 'admin.coupon.index'],
            ['role_id' => 15, 'name' => 'admin.coupon.store'],
            ['role_id' => 15, 'name' => 'admin.coupon.update'],
            ['role_id' => 15, 'name' => 'admin.coupon.edit'],
            ['role_id' => 15, 'name' => 'admin.coupon.destroy'],
            ['role_id' => 15, 'name' => 'admin.coupon.show'],
            ['role_id' => 16, 'name' => 'admin.terms'],
            ['role_id' => 16, 'name' => 'admin.refund'],
            ['role_id' => 16, 'name' => 'admin.aboutus'],
            ['role_id' => 16, 'name' => 'admin.replacement'],
            ['role_id' => 16, 'name' => 'admin.howitworks'],
            ['role_id' => 16, 'name' => 'admin.privacy'],
            ['role_id' => 16, 'name' => 'admin.save_terms'],
            ['role_id' => 16, 'name' => 'admin.save_refund'],
            ['role_id' => 16, 'name' => 'admin.save_replacement'],
            ['role_id' => 16, 'name' => 'admin.save_privacy'],
            ['role_id' => 16, 'name' => 'admin.save_howitworks'],
            ['role_id' => 16, 'name' => 'admin.save_aboutus'],
            ['role_id' => 17, 'name' => 'admin.blog.create'],
            ['role_id' => 17, 'name' => 'admin.blog.index'],
            ['role_id' => 17, 'name' => 'admin.blog.store'],
            ['role_id' => 17, 'name' => 'admin.blog.update'],
            ['role_id' => 17, 'name' => 'admin.blog.edit'],
            ['role_id' => 17, 'name' => 'admin.blog.destroy'],
            ['role_id' => 17, 'name' => 'admin.blog.show'],
            ['role_id' => 18, 'name' => 'admin.order.pending'],
            ['role_id' => 18, 'name' => 'admin.add-comment'],
            ['role_id' => 18, 'name' => 'admin.order.accepted'],
            ['role_id' => 18, 'name' => 'admin.order.rejected'],
            ['role_id' => 18, 'name' => 'admin.order.dispatched'],
            ['role_id' => 18, 'name' => 'admin.order.ready'],
            ['role_id' => 18, 'name' => 'admin.order.readyToShip'],
            ['role_id' => 18, 'name' => 'admin.order.delivered'],
            ['role_id' => 18, 'name' => 'admin.order.history'],
            ['role_id' => 18, 'name' => 'admin.order.details'],
            ['role_id' => 18, 'name' => 'admin.order.index'],
            ['role_id' => 18, 'name' => 'admin.order.status.accept'],
            ['role_id' => 18, 'name' => 'admin.order.status.deliver'],
            ['role_id' => 18, 'name' => 'admin.order.status.dispatch'],
            ['role_id' => 18, 'name' => 'admin.order.status.reject'],
            ['role_id' => 19, 'name' => 'admin.transaction.user'],
            ['role_id' => 19, 'name' => 'admin.transaction.vendor'],
            ['role_id' => 20, 'name' => 'admin.withdraw-account.index'],
            ['role_id' => 20, 'name' => 'admin.withdraw-account.store'],
            ['role_id' => 20, 'name' => 'admin.withdraw-account.update'],
            ['role_id' => 20, 'name' => 'admin.withdraw-account.edit'],
            ['role_id' => 20, 'name' => 'admin.withdraw-account.destroy'],
            ['role_id' => 20, 'name' => 'admin.withdraw-account.show'],
            ['role_id' => 20, 'name' => 'admin.accept'],
            ['role_id' => 20, 'name' => 'admin.reject'],
            ['role_id' => 20, 'name' => 'admin.accept'],
            ['role_id' => 20, 'name' => 'admin.accept'],
            ['role_id' => 21, 'name' => 'admin.withdraw.index'],
            ['role_id' => 21, 'name' => 'admin.withdraw.store'],
            ['role_id' => 21, 'name' => 'admin.withdraw.update'],
            ['role_id' => 21, 'name' => 'admin.withdraw.edit'],
            ['role_id' => 21, 'name' => 'admin.withdraw.destroy'],
            ['role_id' => 21, 'name' => 'admin.withdraw.show'],
            ['role_id' => 21, 'name' => 'admin.withdraw.accept'],
            ['role_id' => 21, 'name' => 'admin.withdraw.reject'],
            ['role_id' => 21, 'name' => 'admin.withdraw.account.accept'],
            ['role_id' => 21, 'name' => 'admin.withdraw.account.reject'],
            ['role_id' => 22, 'name' => 'admin.slider.index'],
            ['role_id' => 22, 'name' => 'admin.slider.store'],
            ['role_id' => 22, 'name' => 'admin.slider.update'],
            ['role_id' => 22, 'name' => 'admin.slider.edit'],
            ['role_id' => 22, 'name' => 'admin.slider.destroy'],
            ['role_id' => 22, 'name' => 'admin.slider.show'],
            ['role_id' => 23, 'name' => 'admin.banner.index'],
            ['role_id' => 23, 'name' => 'admin.banner.store'],
            ['role_id' => 23, 'name' => 'admin.banner.update'],
            ['role_id' => 23, 'name' => 'admin.banner.edit'],
            ['role_id' => 23, 'name' => 'admin.banner.destroy'],
            ['role_id' => 23, 'name' => 'admin.banner.show'],
            ['role_id' => 24, 'name' => 'admin.newsletter'],
            ['role_id' => 24, 'name' => 'admin.sendnewsletter'],
            ['role_id' => 25, 'name' => 'admin.ticket.index'],
            ['role_id' => 25, 'name' => 'admin.ticket.store'],
            ['role_id' => 25, 'name' => 'admin.ticket.update'],
            ['role_id' => 25, 'name' => 'admin.ticket.edit'],
            ['role_id' => 25, 'name' => 'admin.ticket.destroy'],
            ['role_id' => 25, 'name' => 'admin.ticket.show'],
            ['role_id' => 25, 'name' => 'admin.reply.store'],
            ['role_id' => 25, 'name' => 'admin.get-tickets'],
            ['role_id' => 26, 'name' => 'admin.news-ticker.index'],
            ['role_id' => 26, 'name' => 'admin.news-ticker.update'],
            ['role_id' => 27, 'name' => 'admin.tax.index'],
            ['role_id' => 27, 'name' => 'admin.tax.store'],
            ['role_id' => 28, 'name' => 'admin.accountDashboard'],
            ['role_id' => 28, 'name' => 'admin.transaction.company'],
           
        ]);
    }
}
